# Generated by Django 4.2.7 on 2025-09-07 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que agregó la observación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='caso',
            name='creado_por',
            field=models.ForeignKey(help_text='Usuario que creó el caso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='caso',
            name='juez_asignado',
            field=models.ForeignKey(help_text='Juez de Paz responsable del caso', on_delete=django.db.models.deletion.PROTECT, related_name='casos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Juez Asignado'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='caso',
            field=models.ForeignKey(help_text='Caso al que pertenece el adjunto', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='casos.caso', verbose_name='Caso'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='subido_por',
            field=models.ForeignKey(help_text='Usuario que subió el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['numero_caso'], name='casos_caso_numero__75eba2_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['juez_asignado', 'estado'], name='casos_caso_juez_as_622fae_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['cedula_solicitante'], name='casos_caso_cedula__fa34fb_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['fecha_registro'], name='casos_caso_fecha_r_60b865_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['estado', 'fecha_limite'], name='casos_caso_estado_0fe9cc_idx'),
        ),
    ]
