# Generated by Django 4.2.7 on 2025-10-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('en_tramite', 'En Trámite'), ('resuelto', 'Resuelto'), ('no_resuelto', 'No Resuelto'), ('archivado', 'Archivado')], default='en_tramite', help_text='Estado actual del caso', max_length=15, verbose_name='Estado del Caso'),
        ),
    ]
