# Generated by Django 4.2.7 on 2025-10-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_alter_caso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='bloque_residencial',
            field=models.CharField(choices=[('BLOQUE_15', 'Bloque 15'), ('BLOQUE_16', 'Bloque 16'), ('BLOQUE_17', 'Bloque 17'), ('BLOQUE_18', 'Bloque 18'), ('BLOQUE_19', 'Bloque 19'), ('BLOQUE_20', 'Bloque 20'), ('BLOQUE_21', 'Bloque 21'), ('BLOQUE_22P', 'Bloque 22P'), ('BLOQUE_23P', 'Bloque 23P'), ('BLOQUE_24P', 'Bloque 24P'), ('BLOQUE_25P', 'Bloque 25P')], help_text='Bloque residencial donde ocurre el conflicto', max_length=10, verbose_name='Bloque Residencial'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='tipo_conflicto',
            field=models.CharField(choices=[('vecinal', 'Vecinal'), ('individual', 'Individual'), ('comunitario', 'Comunitario'), ('contravencion', 'Contravención sin Privación de Libertad'), ('obligacion_patrimonial', 'Obligación Patrimonial (hasta 5 salarios básicos)'), ('otro', 'Otro')], help_text='Tipo de conflicto que se presenta', max_length=30, verbose_name='Tipo de Conflicto'),
        ),
    ]
